let germanyUniversities = [

{
  name: "TU Berlin",
  country: "Germany",
  course: "Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Technical University of Munich",
  country: "Germany",
  course: "Computer Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "320",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "RWTH Aachen University",
  country: "Germany",
  course: "Mechanical Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "315",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Stuttgart",
  country: "Germany",
  course: "Automobile Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Freiburg",
  country: "Germany",
  course: "Environmental Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "300",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Heidelberg University",
  country: "Germany",
  course: "Medicine",
  level: "Masters",
  intake: "Fall",
  ielts: "7.0",
  gre: "315",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Mannheim",
  country: "Germany",
  course: "Business",
  level: "MBA",
  intake: "Spring",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "650",
  budget: "Low"
},
{
  name: "University of Hamburg",
  country: "Germany",
  course: "Economics",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "300",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Bonn",
  country: "Germany",
  course: "Physics",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Cologne",
  country: "Germany",
  course: "Business",
  level: "Bachelors",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Bremen",
  country: "Germany",
  course: "Robotics",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "300",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Leipzig",
  country: "Germany",
  course: "Biotechnology",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "300",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Duisburg Essen",
  country: "Germany",
  course: "Data Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "305",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Potsdam",
  country: "Germany",
  course: "Artificial Intelligence",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Erlangen",
  country: "Germany",
  course: "Electrical Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Karlsruhe Institute of Technology",
  country: "Germany",
  course: "Computer Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "315",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "TU Darmstadt",
  country: "Germany",
  course: "Cyber Security",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "TU Dortmund",
  country: "Germany",
  course: "Mechanical Engineering",
  level: "Bachelors",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Kassel",
  country: "Germany",
  course: "Renewable Energy",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "300",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Jena",
  country: "Germany",
  course: "Optics",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "300",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Magdeburg",
  country: "Germany",
  course: "Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "300",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Rostock",
  country: "Germany",
  course: "Marine Science",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Ulm",
  country: "Germany",
  course: "Medicine",
  level: "Masters",
  intake: "Fall",
  ielts: "7.0",
  gre: "310",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Siegen",
  country: "Germany",
  course: "Computer Science",
  level: "Bachelors",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Hildesheim",
  country: "Germany",
  course: "Data Analytics",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "300",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Regensburg",
  country: "Germany",
  course: "Business",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "550",
  budget: "Low"
},
{
  name: "University of Passau",
  country: "Germany",
  course: "MBA",
  level: "MBA",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "600",
  budget: "Low"
},
{
  name: "University of Bayreuth",
  country: "Germany",
  course: "Economics",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Trier",
  country: "Germany",
  course: "Law",
  level: "Masters",
  intake: "Spring",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Wuppertal",
  country: "Germany",
  course: "Architecture",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
}

,
{
  name: "Ludwig Maximilian University Munich",
  country: "Germany",
  course: "Medicine",
  level: "Masters",
  intake: "Fall",
  ielts: "7.0",
  gre: "315",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Humboldt University Berlin",
  country: "Germany",
  course: "Political Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "300",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Free University of Berlin",
  country: "Germany",
  course: "International Relations",
  level: "Masters",
  intake: "Spring",
  ielts: "6.5",
  gre: "300",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "TU Dresden",
  country: "Germany",
  course: "Civil Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Hannover",
  country: "Germany",
  course: "Mechanical Engineering",
  level: "Bachelors",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Kiel",
  country: "Germany",
  course: "Marine Biology",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Erfurt",
  country: "Germany",
  course: "Education",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Augsburg",
  country: "Germany",
  course: "Business Analytics",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "300",
  gmat: "550",
  budget: "Low"
},
{
  name: "University of Giessen",
  country: "Germany",
  course: "Agriculture",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Marburg",
  country: "Germany",
  course: "Biochemistry",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "300",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Konstanz",
  country: "Germany",
  course: "Computer Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Saarland",
  country: "Germany",
  course: "Cyber Security",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Hohenheim",
  country: "Germany",
  course: "Agribusiness",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "550",
  budget: "Low"
},
{
  name: "University of Bielefeld",
  country: "Germany",
  course: "Data Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "305",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Chemnitz",
  country: "Germany",
  course: "Automotive Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Greifswald",
  country: "Germany",
  course: "Medicine",
  level: "Bachelors",
  intake: "Spring",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Mainz",
  country: "Germany",
  course: "Media Studies",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Munster",
  country: "Germany",
  course: "Law",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Tubingen",
  country: "Germany",
  course: "Neuroscience",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Gottingen",
  country: "Germany",
  course: "Physics",
  level: "Masters",
  intake: "Spring",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Low"
}

,
{
  name: "FH Aachen University of Applied Sciences",
  country: "Germany",
  course: "Engineering",
  level: "Bachelors",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "HTW Berlin",
  country: "Germany",
  course: "Business Informatics",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Hochschule Darmstadt",
  country: "Germany",
  course: "Computer Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "300",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Hochschule Bremen",
  country: "Germany",
  course: "Shipping and Logistics",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Hochschule Hannover",
  country: "Germany",
  course: "Mechanical Engineering",
  level: "Bachelors",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Hochschule Fulda",
  country: "Germany",
  course: "Public Health",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Hochschule Trier",
  country: "Germany",
  course: "Architecture",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Hochschule Bonn Rhein Sieg",
  country: "Germany",
  course: "Cyber Security",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "305",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Hochschule Karlsruhe",
  country: "Germany",
  course: "Automotive Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Hochschule Mannheim",
  country: "Germany",
  course: "Business Administration",
  level: "MBA",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "550",
  budget: "Low"
},
{
  name: "Hochschule Munich",
  country: "Germany",
  course: "Engineering",
  level: "Bachelors",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Hochschule Osnabrück",
  country: "Germany",
  course: "Agriculture",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Hochschule Ruhr West",
  country: "Germany",
  course: "Data Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "300",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Hochschule Weihenstephan",
  country: "Germany",
  course: "Food Technology",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Hochschule Niederrhein",
  country: "Germany",
  course: "Textile Engineering",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Hochschule Anhalt",
  country: "Germany",
  course: "Architecture",
  level: "Bachelors",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Hochschule Augsburg",
  country: "Germany",
  course: "International Management",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "550",
  budget: "Low"
},
{
  name: "Hochschule Bielefeld",
  country: "Germany",
  course: "Engineering Management",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "300",
  gmat: "550",
  budget: "Low"
},
{
  name: "Hochschule Coburg",
  country: "Germany",
  course: "Automotive Engineering",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "300",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Hochschule Esslingen",
  country: "Germany",
  course: "Automotive Systems",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Low"
}



];