let usaUniversities = [

{
name:"Harvard University",
country:"USA",
course:"Business",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"320",
gmat:"700",
budget:"Very High"
},
{
name:"Stanford University",
country:"USA",
course:"Computer Science",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"325",
gmat:"Not Required",
budget:"Very High"
},
{
name:"Massachusetts Institute of Technology",
country:"USA",
course:"Engineering",
level:"Masters",
intake:"Spring",
ielts:"7.0",
gre:"325",
gmat:"Not Required",
budget:"Very High"
},
{
name:"California Institute of Technology",
country:"USA",
course:"Physics",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"320",
gmat:"Not Required",
budget:"Very High"
},
{
name:"University of Chicago",
country:"USA",
course:"Economics",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"320",
gmat:"650",
budget:"Very High"
},
{
name:"Princeton University",
country:"USA",
course:"Mathematics",
level:"Masters",
intake:"Spring",
ielts:"7.0",
gre:"320",
gmat:"Not Required",
budget:"Very High"
},
{
name:"Yale University",
country:"USA",
course:"Law",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"315",
gmat:"650",
budget:"Very High"
},
{
name:"Columbia University",
country:"USA",
course:"Journalism",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"315",
gmat:"650",
budget:"Very High"
},
{
name:"University of Pennsylvania",
country:"USA",
course:"MBA",
level:"MBA",
intake:"Spring",
ielts:"7.0",
gre:"320",
gmat:"700",
budget:"Very High"
},
{
name:"Johns Hopkins University",
country:"USA",
course:"Public Health",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"315",
gmat:"Not Required",
budget:"High"
},
{
name:"Cornell University",
country:"USA",
course:"Agriculture",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"315",
gmat:"Not Required",
budget:"Very High"
},
{
name:"Duke University",
country:"USA",
course:"Medicine",
level:"Masters",
intake:"Spring",
ielts:"7.0",
gre:"320",
gmat:"Not Required",
budget:"Very High"
},
{
name:"Northwestern University",
country:"USA",
course:"Marketing",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"315",
gmat:"650",
budget:"Very High"
},
{
name:"University of California Berkeley",
country:"USA",
course:"Data Science",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"320",
gmat:"Not Required",
budget:"High"
},
{
name:"University of California Los Angeles",
country:"USA",
course:"Film Studies",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"315",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Michigan",
country:"USA",
course:"Mechanical Engineering",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"315",
gmat:"Not Required",
budget:"High"
},
{
name:"New York University",
country:"USA",
course:"Finance",
level:"Masters",
intake:"Spring",
ielts:"7.0",
gre:"315",
gmat:"650",
budget:"Very High"
},
{
name:"Carnegie Mellon University",
country:"USA",
course:"Artificial Intelligence",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"325",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Washington",
country:"USA",
course:"Cyber Security",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"310",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Texas Austin",
country:"USA",
course:"Petroleum Engineering",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"310",
gmat:"Not Required",
budget:"High"
},
{
name:"Georgia Institute of Technology",
country:"USA",
course:"Robotics",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"320",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Wisconsin Madison",
country:"USA",
course:"Biotechnology",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"310",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Illinois Urbana Champaign",
country:"USA",
course:"Computer Science",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"320",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Southern California",
country:"USA",
course:"Business Analytics",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"315",
gmat:"650",
budget:"Very High"
},
{
name:"Boston University",
country:"USA",
course:"Healthcare Management",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"310",
gmat:"600",
budget:"High"
},
{
name:"Boston College",
country:"USA",
course:"Accounting",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"310",
gmat:"650",
budget:"High"
},
{
name:"University of Florida",
country:"USA",
course:"Environmental Science",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Pennsylvania State University",
country:"USA",
course:"Industrial Engineering",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"310",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Ohio State University",
country:"USA",
course:"Supply Chain Management",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"600",
budget:"Medium"
},
{
name:"Arizona State University",
country:"USA",
course:"Information Technology",
level:"Masters",
intake:"Fall",
ielts:"6.0",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Arizona",
country:"USA",
course:"Astronomy",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"305",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Colorado Boulder",
country:"USA",
course:"Aerospace Engineering",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"310",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Minnesota",
country:"USA",
course:"Nursing",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Michigan State University",
country:"USA",
course:"Agriculture",
level:"Masters",
intake:"Fall",
ielts:"6.0",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Maryland",
country:"USA",
course:"Cyber Security",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"310",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Virginia",
country:"USA",
course:"Law",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"315",
gmat:"650",
budget:"High"
},
{
name:"University of North Carolina Chapel Hill",
country:"USA",
course:"Public Health",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"310",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Pittsburgh",
country:"USA",
course:"Pharmacy",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"305",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Cincinnati",
country:"USA",
course:"Architecture",
level:"Masters",
intake:"Spring",
ielts:"6.0",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Indiana University Bloomington",
country:"USA",
course:"Business",
level:"MBA",
intake:"Fall",
ielts:"6.5",
gre:"310",
gmat:"650",
budget:"Medium"
}

];