let nzUniversities = [

{
name:"University of Auckland",
country:"New Zealand",
course:"Computer Science",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Otago",
country:"New Zealand",
course:"Medicine",
level:"Masters",
intake:"Spring",
ielts:"7.0",
gre:"310",
gmat:"Not Required",
budget:"High"
},
{
name:"Victoria University of Wellington",
country:"New Zealand",
course:"Law",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"Not Required",
gmat:"550",
budget:"High"
},
{
name:"University of Canterbury",
country:"New Zealand",
course:"Engineering",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"High"
},
{
name:"Massey University",
country:"New Zealand",
course:"Business",
level:"MBA",
intake:"Fall",
ielts:"6.5",
gre:"Not Required",
gmat:"600",
budget:"Medium"
},
{
name:"University of Waikato",
country:"New Zealand",
course:"Data Science",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Lincoln University",
country:"New Zealand",
course:"Agriculture",
level:"Bachelors",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Auckland University of Technology",
country:"New Zealand",
course:"Artificial Intelligence",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Unitec Institute of Technology",
country:"New Zealand",
course:"IT",
level:"Diploma",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Manukau Institute of Technology",
country:"New Zealand",
course:"Hospitality",
level:"Diploma",
intake:"Spring",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Eastern Institute of Technology",
country:"New Zealand",
course:"Nursing",
level:"Bachelors",
intake:"Fall",
ielts:"6.5",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Wellington Institute of Technology",
country:"New Zealand",
course:"Cyber Security",
level:"Diploma",
intake:"Spring",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Nelson Marlborough Institute of Technology",
country:"New Zealand",
course:"Business",
level:"Diploma",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Otago Polytechnic",
country:"New Zealand",
course:"Engineering",
level:"Diploma",
intake:"Spring",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Ara Institute of Canterbury",
country:"New Zealand",
course:"Construction Management",
level:"Diploma",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Southern Institute of Technology",
country:"New Zealand",
course:"Computer Science",
level:"Diploma",
intake:"Spring",
ielts:"5.5",
gre:"Not Required",
gmat:"Not Required",
budget:"Low"
},
{
name:"Whitireia New Zealand",
country:"New Zealand",
course:"Nursing",
level:"Diploma",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Western Institute of Technology at Taranaki",
country:"New Zealand",
course:"Mechanical Engineering",
level:"Diploma",
intake:"Spring",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Toi Ohomai Institute of Technology",
country:"New Zealand",
course:"Hospitality",
level:"Diploma",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"NorthTec",
country:"New Zealand",
course:"Automotive Engineering",
level:"Diploma",
intake:"Spring",
ielts:"5.5",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
}
,
{
name:"New Zealand Tertiary College",
country:"New Zealand",
course:"Education",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"ICL Graduate Business School",
country:"New Zealand",
course:"MBA",
level:"MBA",
intake:"Spring",
ielts:"6.5",
gre:"Not Required",
gmat:"600",
budget:"Medium"
},
{
name:"AIS St Helens",
country:"New Zealand",
course:"Business",
level:"Masters",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"550",
budget:"Medium"
},
{
name:"UP Education",
country:"New Zealand",
course:"IT",
level:"Diploma",
intake:"Spring",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"New Zealand School of Education",
country:"New Zealand",
course:"Education",
level:"Diploma",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Cornell Institute of Business and Technology",
country:"New Zealand",
course:"Business",
level:"Diploma",
intake:"Spring",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Queens Academic Group",
country:"New Zealand",
course:"Hospitality",
level:"Diploma",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"NZMA",
country:"New Zealand",
course:"Culinary Arts",
level:"Diploma",
intake:"Spring",
ielts:"5.5",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Elite School of Beauty and Spa",
country:"New Zealand",
course:"Beauty Therapy",
level:"Diploma",
intake:"Fall",
ielts:"5.5",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Whitecliffe College",
country:"New Zealand",
course:"Fashion Design",
level:"Bachelors",
intake:"Spring",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Media Design School",
country:"New Zealand",
course:"Animation",
level:"Bachelors",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Yoobee College of Creative Innovation",
country:"New Zealand",
course:"Graphic Design",
level:"Diploma",
intake:"Spring",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"SAE Institute New Zealand",
country:"New Zealand",
course:"Audio Engineering",
level:"Diploma",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Laidlaw College",
country:"New Zealand",
course:"Theology",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Carey Baptist College",
country:"New Zealand",
course:"Religious Studies",
level:"Bachelors",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"The University of Auckland Business School",
country:"New Zealand",
course:"MBA",
level:"MBA",
intake:"Fall",
ielts:"6.5",
gre:"Not Required",
gmat:"650",
budget:"High"
},
{
name:"Victoria Business School Wellington",
country:"New Zealand",
course:"Finance",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"600",
budget:"High"
},
{
name:"Otago Business School",
country:"New Zealand",
course:"Business Analytics",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"600",
budget:"High"
},
{
name:"Waikato Management School",
country:"New Zealand",
course:"Marketing",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"Not Required",
gmat:"550",
budget:"High"
},
{
name:"Eastern Institute of Technology Auckland",
country:"New Zealand",
course:"Healthcare Management",
level:"Diploma",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
}
];