const universities = [

{
name:"University of Oxford",
country:"UK",
course:"Law",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"320",
gmat:"650",
budget:"Very High"
},
{
name:"University of Cambridge",
country:"UK",
course:"Engineering",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"320",
gmat:"Not Required",
budget:"Very High"
},
{
name:"Imperial College London",
country:"UK",
course:"Computer Science",
level:"Masters",
intake:"Spring",
ielts:"7.0",
gre:"320",
gmat:"Not Required",
budget:"Very High"
},
{
name:"University College London",
country:"UK",
course:"Business Analytics",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"310",
gmat:"600",
budget:"Very High"
},
{
name:"London School of Economics",
country:"UK",
course:"Economics",
level:"Masters",
intake:"Spring",
ielts:"7.0",
gre:"320",
gmat:"650",
budget:"Very High"
},
{
name:"King's College London",
country:"UK",
course:"Medicine",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"310",
gmat:"Not Required",
budget:"Very High"
},
{
name:"University of Edinburgh",
country:"UK",
course:"Artificial Intelligence",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"310",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Manchester",
country:"UK",
course:"Mechanical Engineering",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Bristol",
country:"UK",
course:"Civil Engineering",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Warwick",
country:"UK",
course:"MBA",
level:"MBA",
intake:"Fall",
ielts:"6.5",
gre:"310",
gmat:"650",
budget:"High"
},
{
name:"University of Glasgow",
country:"UK",
course:"Finance",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"600",
budget:"High"
},
{
name:"University of Birmingham",
country:"UK",
course:"Data Science",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Leeds",
country:"UK",
course:"Cyber Security",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Sheffield",
country:"UK",
course:"Architecture",
level:"Masters",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Nottingham",
country:"UK",
course:"Biotechnology",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Southampton",
country:"UK",
course:"Marine Engineering",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"High"
},
{
name:"University of York",
country:"UK",
course:"Psychology",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"Not Required",
gmat:"Not Required",
budget:"High"
},
{
name:"University of Exeter",
country:"UK",
course:"Marketing",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"Not Required",
gmat:"550",
budget:"High"
},
{
name:"Durham University",
country:"UK",
course:"International Relations",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"High"
},
{
name:"Queen Mary University of London",
country:"UK",
course:"Law",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"550",
budget:"High"
}
,
{
name:"University of Liverpool",
country:"UK",
course:"Business",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"550",
budget:"High"
},
{
name:"University of Leicester",
country:"UK",
course:"Computer Science",
level:"Masters",
intake:"Fall",
ielts:"6.0",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Sussex",
country:"UK",
course:"Artificial Intelligence",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Surrey",
country:"UK",
course:"Hospitality Management",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"Not Required",
gmat:"550",
budget:"Medium"
},
{
name:"University of Reading",
country:"UK",
course:"Finance",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"600",
budget:"Medium"
},
{
name:"University of Bath",
country:"UK",
course:"Mechanical Engineering",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"310",
gmat:"Not Required",
budget:"High"
},
{
name:"Loughborough University",
country:"UK",
course:"Sports Management",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"Not Required",
gmat:"550",
budget:"High"
},
{
name:"Lancaster University",
country:"UK",
course:"Business Analytics",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"600",
budget:"High"
},
{
name:"University of East Anglia",
country:"UK",
course:"Pharmacy",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Kent",
country:"UK",
course:"Law",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"550",
budget:"Medium"
},
{
name:"University of Essex",
country:"UK",
course:"Economics",
level:"Masters",
intake:"Spring",
ielts:"6.0",
gre:"300",
gmat:"550",
budget:"Medium"
},
{
name:"University of Hull",
country:"UK",
course:"Marine Biology",
level:"Masters",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Lincoln",
country:"UK",
course:"Agriculture",
level:"Bachelors",
intake:"Spring",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Portsmouth",
country:"UK",
course:"Cyber Security",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Plymouth",
country:"UK",
course:"Civil Engineering",
level:"Masters",
intake:"Spring",
ielts:"6.0",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Brighton",
country:"UK",
course:"Fashion Design",
level:"Masters",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Hertfordshire",
country:"UK",
course:"Data Science",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Coventry University",
country:"UK",
course:"Automobile Engineering",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Northumbria University",
country:"UK",
course:"MBA",
level:"MBA",
intake:"Spring",
ielts:"6.5",
gre:"Not Required",
gmat:"600",
budget:"Medium"
},
{
name:"Manchester Metropolitan University",
country:"UK",
course:"Marketing",
level:"Masters",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"550",
budget:"Medium"
}
];