let canadaUniversities = [

{
  name: "University of Toronto",
  country: "Canada",
  course: "Computer Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Very High"
},
{
  name: "University of British Columbia",
  country: "Canada",
  course: "Data Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Very High"
},
{
  name: "McGill University",
  country: "Canada",
  course: "Business",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "650",
  budget: "Very High"
},
{
  name: "University of Alberta",
  country: "Canada",
  course: "Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "300",
  gmat: "Not Required",
  budget: "High"
},
{
  name: "University of Waterloo",
  country: "Canada",
  course: "Computer Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "High"
},
{
  name: "Western University",
  country: "Canada",
  course: "MBA",
  level: "MBA",
  intake: "Spring",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "650",
  budget: "High"
},
{
  name: "University of Calgary",
  country: "Canada",
  course: "Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "300",
  gmat: "Not Required",
  budget: "High"
},
{
  name: "Queen's University",
  country: "Canada",
  course: "Business",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "650",
  budget: "High"
},
{
  name: "Dalhousie University",
  country: "Canada",
  course: "Cyber Security",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Simon Fraser University",
  country: "Canada",
  course: "Data Science",
  level: "Masters",
  intake: "Spring",
  ielts: "6.5",
  gre: "300",
  gmat: "Not Required",
  budget: "High"
},
{
  name: "University of Ottawa",
  country: "Canada",
  course: "Computer Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "300",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "York University",
  country: "Canada",
  course: "Business",
  level: "MBA",
  intake: "Spring",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "600",
  budget: "Medium"
},
{
  name: "Concordia University",
  country: "Canada",
  course: "Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "300",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Carleton University",
  country: "Canada",
  course: "IT",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "University of Manitoba",
  country: "Canada",
  course: "Agriculture",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "University of Saskatchewan",
  country: "Canada",
  course: "Biotechnology",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Memorial University of Newfoundland",
  country: "Canada",
  course: "Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Windsor",
  country: "Canada",
  course: "Automotive Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "300",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "University of Regina",
  country: "Canada",
  course: "Computer Science",
  level: "Masters",
  intake: "Spring",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Brock University",
  country: "Canada",
  course: "Business",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "550",
  budget: "Medium"
},
{
  name: "Lakehead University",
  country: "Canada",
  course: "Civil Engineering",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
}

{
  name: "Trent University",
  country: "Canada",
  course: "Business",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "550",
  budget: "Medium"
},
{
  name: "Wilfrid Laurier University",
  country: "Canada",
  course: "MBA",
  level: "MBA",
  intake: "Spring",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "600",
  budget: "Medium"
},
{
  name: "Ontario Tech University",
  country: "Canada",
  course: "Cyber Security",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "300",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Mount Saint Vincent University",
  country: "Canada",
  course: "Education",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Saint Mary's University",
  country: "Canada",
  course: "Business",
  level: "MBA",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "600",
  budget: "Medium"
},
{
  name: "Acadia University",
  country: "Canada",
  course: "Biology",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Cape Breton University",
  country: "Canada",
  course: "Hospitality",
  level: "Bachelors",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "University of Northern British Columbia",
  country: "Canada",
  course: "Environmental Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Thompson Rivers University",
  country: "Canada",
  course: "Business",
  level: "Bachelors",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "University of Lethbridge",
  country: "Canada",
  course: "Computer Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "MacEwan University",
  country: "Canada",
  course: "Business",
  level: "Bachelors",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Mount Royal University",
  country: "Canada",
  course: "Marketing",
  level: "Bachelors",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Brandon University",
  country: "Canada",
  course: "Arts",
  level: "Bachelors",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Low"
},
{
  name: "Nipissing University",
  country: "Canada",
  course: "Education",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Laurentian University",
  country: "Canada",
  course: "Mining Engineering",
  level: "Masters",
  intake: "Spring",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Algoma University",
  country: "Canada",
  course: "Computer Science",
  level: "Bachelors",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "University Canada West",
  country: "Canada",
  course: "MBA",
  level: "MBA",
  intake: "Spring",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "550",
  budget: "Medium"
},
{
  name: "Fairleigh Dickinson University Canada",
  country: "Canada",
  course: "Business",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "550",
  budget: "High"
},
{
  name: "Royal Roads University",
  country: "Canada",
  course: "Leadership",
  level: "Masters",
  intake: "Spring",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
}

];