let franceUniversities = [

{
  name: "Sorbonne University",
  country: "France",
  course: "Arts",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université Paris Saclay",
  country: "France",
  course: "Data Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université PSL",
  country: "France",
  course: "Physics",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "École Polytechnique",
  country: "France",
  course: "Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "7.0",
  gre: "320",
  gmat: "Not Required",
  budget: "Very High"
},
{
  name: "HEC Paris",
  country: "France",
  course: "MBA",
  level: "MBA",
  intake: "Spring",
  ielts: "7.0",
  gre: "Not Required",
  gmat: "700",
  budget: "Very High"
},
{
  name: "ESSEC Business School",
  country: "France",
  course: "Business",
  level: "MBA",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "680",
  budget: "Very High"
},
{
  name: "ESCP Business School",
  country: "France",
  course: "Management",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "650",
  budget: "Very High"
},
{
  name: "EDHEC Business School",
  country: "France",
  course: "Finance",
  level: "Masters",
  intake: "Spring",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "650",
  budget: "High"
},
{
  name: "EM Lyon Business School",
  country: "France",
  course: "Business Analytics",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "650",
  budget: "High"
},
{
  name: "Grenoble Ecole de Management",
  country: "France",
  course: "Marketing",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "600",
  budget: "High"
},
{
  name: "KEDGE Business School",
  country: "France",
  course: "International Business",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "600",
  budget: "High"
},
{
  name: "NEOMA Business School",
  country: "France",
  course: "Luxury Brand Management",
  level: "Masters",
  intake: "Spring",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "600",
  budget: "High"
},
{
  name: "SKEMA Business School",
  country: "France",
  course: "Data Analytics",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "300",
  gmat: "600",
  budget: "High"
},
{
  name: "Audencia Business School",
  country: "France",
  course: "Finance",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "600",
  budget: "High"
},
{
  name: "Toulouse Business School",
  country: "France",
  course: "Business",
  level: "Masters",
  intake: "Spring",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "600",
  budget: "High"
},
{
  name: "INSEEC Business School",
  country: "France",
  course: "Marketing",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "550",
  budget: "High"
},
{
  name: "ISC Paris",
  country: "France",
  course: "Business",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "550",
  budget: "High"
},
{
  name: "IESEG School of Management",
  country: "France",
  course: "Management",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "600",
  budget: "High"
},
{
  name: "ESSCA School of Management",
  country: "France",
  course: "Finance",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "550",
  budget: "High"
},
{
  name: "Montpellier Business School",
  country: "France",
  course: "Business Analytics",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "300",
  gmat: "600",
  budget: "High"
}
{
  name: "Rennes School of Business",
  country: "France",
  course: "International Business",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "600",
  budget: "High"
},
{
  name: "Excelia Business School",
  country: "France",
  course: "Finance",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "550",
  budget: "High"
},
{
  name: "Paris School of Business",
  country: "France",
  course: "MBA",
  level: "MBA",
  intake: "Fall",
  ielts: "6.5",
  gre: "Not Required",
  gmat: "650",
  budget: "High"
},
{
  name: "EBS Paris",
  country: "France",
  course: "Business",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "550",
  budget: "High"
},
{
  name: "Institut Polytechnique de Paris",
  country: "France",
  course: "Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "315",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université de Lyon",
  country: "France",
  course: "Computer Science",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "300",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université de Lille",
  country: "France",
  course: "Business",
  level: "Bachelors",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université de Bordeaux",
  country: "France",
  course: "Wine Business",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université de Strasbourg",
  country: "France",
  course: "Medicine",
  level: "Masters",
  intake: "Fall",
  ielts: "7.0",
  gre: "310",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université de Nantes",
  country: "France",
  course: "Engineering",
  level: "Bachelors",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université de Montpellier",
  country: "France",
  course: "Biotechnology",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "300",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université de Rennes",
  country: "France",
  course: "Cyber Security",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "305",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université de Grenoble Alpes",
  country: "France",
  course: "Artificial Intelligence",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "310",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université de Toulouse",
  country: "France",
  course: "Aerospace Engineering",
  level: "Masters",
  intake: "Fall",
  ielts: "6.5",
  gre: "315",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université de Nice",
  country: "France",
  course: "Hospitality",
  level: "Bachelors",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université de Dijon",
  country: "France",
  course: "Business",
  level: "Bachelors",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université de Reims",
  country: "France",
  course: "Marketing",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "550",
  budget: "Medium"
},
{
  name: "Université de Rouen",
  country: "France",
  course: "Engineering",
  level: "Bachelors",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université de Caen",
  country: "France",
  course: "Data Science",
  level: "Masters",
  intake: "Spring",
  ielts: "6.0",
  gre: "300",
  gmat: "Not Required",
  budget: "Medium"
},
{
  name: "Université de Tours",
  country: "France",
  course: "Finance",
  level: "Masters",
  intake: "Fall",
  ielts: "6.0",
  gre: "Not Required",
  gmat: "550",
  budget: "Medium"
}
];