let spainUniversities = [

{
name:"University of Barcelona",
country:"Spain",
course:"Business",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"550",
budget:"Medium"
},
{
name:"Autonomous University of Barcelona",
country:"Spain",
course:"Data Science",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Complutense University of Madrid",
country:"Spain",
course:"Law",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"Not Required",
gmat:"550",
budget:"Medium"
},
{
name:"Autonomous University of Madrid",
country:"Spain",
course:"Psychology",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Valencia",
country:"Spain",
course:"Computer Science",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Granada",
country:"Spain",
course:"Artificial Intelligence",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Seville",
country:"Spain",
course:"Mechanical Engineering",
level:"Bachelors",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Zaragoza",
country:"Spain",
course:"Civil Engineering",
level:"Masters",
intake:"Spring",
ielts:"6.0",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Salamanca",
country:"Spain",
course:"Medicine",
level:"Masters",
intake:"Fall",
ielts:"7.0",
gre:"310",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Malaga",
country:"Spain",
course:"Business Analytics",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"600",
budget:"Medium"
},
{
name:"University of Alicante",
country:"Spain",
course:"Hospitality",
level:"Bachelors",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Murcia",
country:"Spain",
course:"Biotechnology",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Valladolid",
country:"Spain",
course:"Architecture",
level:"Masters",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Oviedo",
country:"Spain",
course:"Finance",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"550",
budget:"Medium"
},
{
name:"University of La Laguna",
country:"Spain",
course:"Marine Science",
level:"Masters",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Cantabria",
country:"Spain",
course:"Cyber Security",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Cordoba",
country:"Spain",
course:"Agriculture",
level:"Bachelors",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Extremadura",
country:"Spain",
course:"Nursing",
level:"Bachelors",
intake:"Spring",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Jaen",
country:"Spain",
course:"MBA",
level:"MBA",
intake:"Fall",
ielts:"6.5",
gre:"Not Required",
gmat:"600",
budget:"Medium"
},
{
name:"University of Leon",
country:"Spain",
course:"Economics",
level:"Masters",
intake:"Spring",
ielts:"6.0",
gre:"Not Required",
gmat:"550",
budget:"Medium"
}
,
{
name:"University of Vigo",
country:"Spain",
course:"Computer Science",
level:"Bachelors",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"University of Navarra",
country:"Spain",
course:"Business",
level:"MBA",
intake:"Fall",
ielts:"7.0",
gre:"320",
gmat:"650",
budget:"High"
},
{
name:"University of Deusto",
country:"Spain",
course:"International Relations",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"550",
budget:"High"
},
{
name:"Pompeu Fabra University",
country:"Spain",
course:"Data Analytics",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Carlos III University of Madrid",
country:"Spain",
course:"Mechanical Engineering",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Polytechnic University of Madrid",
country:"Spain",
course:"Civil Engineering",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"310",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Polytechnic University of Catalonia",
country:"Spain",
course:"Architecture",
level:"Masters",
intake:"Spring",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"Medium"
},
{
name:"Polytechnic University of Valencia",
country:"Spain",
course:"Artificial Intelligence",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"Not Required",
budget:"Medium"
},
{
name:"IE University",
country:"Spain",
course:"Business",
level:"MBA",
intake:"Spring",
ielts:"7.0",
gre:"320",
gmat:"650",
budget:"Very High"
},
{
name:"ESADE Business School",
country:"Spain",
course:"Finance",
level:"MBA",
intake:"Fall",
ielts:"7.0",
gre:"320",
gmat:"650",
budget:"Very High"
},
{
name:"IESE Business School",
country:"Spain",
course:"MBA",
level:"MBA",
intake:"Spring",
ielts:"7.0",
gre:"320",
gmat:"650",
budget:"Very High"
},
{
name:"EAE Business School",
country:"Spain",
course:"Marketing",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"600",
budget:"High"
},
{
name:"EU Business School Spain",
country:"Spain",
course:"Business Analytics",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"300",
gmat:"600",
budget:"High"
},
{
name:"Geneva Business School Spain",
country:"Spain",
course:"International Business",
level:"MBA",
intake:"Fall",
ielts:"6.5",
gre:"Not Required",
gmat:"600",
budget:"High"
},
{
name:"GBSB Global Business School",
country:"Spain",
course:"Digital Marketing",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"Not Required",
gmat:"550",
budget:"High"
},
{
name:"TBS Barcelona",
country:"Spain",
course:"Business",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"300",
gmat:"550",
budget:"High"
},
{
name:"ESIC Business School",
country:"Spain",
course:"Marketing",
level:"MBA",
intake:"Spring",
ielts:"6.5",
gre:"Not Required",
gmat:"600",
budget:"High"
},
{
name:"Schiller International University Spain",
country:"Spain",
course:"Hospitality",
level:"Bachelors",
intake:"Fall",
ielts:"6.0",
gre:"Not Required",
gmat:"Not Required",
budget:"High"
},
{
name:"Les Roches Marbella",
country:"Spain",
course:"Hotel Management",
level:"Masters",
intake:"Spring",
ielts:"6.5",
gre:"Not Required",
gmat:"Not Required",
budget:"High"
},
{
name:"Glion Institute Spain",
country:"Spain",
course:"Luxury Brand Management",
level:"Masters",
intake:"Fall",
ielts:"6.5",
gre:"Not Required",
gmat:"Not Required",
budget:"High"
}
];